INSERT INTO BOOKCLASS (ClassId, ClassName, Location, Color) VALUES
(1, 'Children', 'Floor 1 Column 2', 'Maroon'),
(2, 'Beautiful literature', 'Floor 2 Column 9', 'Purple'),
(3, 'Science fiction', 'Floor 2 Column 4', 'Magenta'),
(4, 'Game', 'Floor 1 Column 6', 'Yellow'),
(5, 'Fantasies', 'Floor 2 Column 5', 'Orange'),
(6, 'Youth', 'Floor 2 Column 3', 'Green'),
(7, 'Adults', 'Floor 1 Column 11', 'Teal'),
(8, 'Russian', 'Floor 3 Column 4', 'Blue'),
(9, 'Audiobooks', 'Floor 1 Column 7', 'Brown'),
(11, 'Children's English', 'Floor 2 Column 7', 'Pink'),
(12, 'Adult English', 'Floor 2 Column 8', 'Gray'),
(13, 'Poetry', 'Floor 3 Column 3', 'Black'),
(14, 'Digital book', 'Floor 1 Column 8', 'White'),
(15, 'French', 'Floor 3 Column 3', 'Silver'),
(16, 'Voltage', 'Floor 2 Column 2', 'Gold'),
(17, 'Comics', 'Floor 1 Column 4', 'Cyan'),
(18, 'Holocaust', 'Floor 3 Column 4', 'Lime'),
(19, 'Legacy', 'Floor 1 Column 10', 'Olive'),
(20, 'Biography', 'Floor 1 Column 9', 'Chocolate'),
(21, 'Judaism', 'Floor 1 Column 5', 'Coral'),
(22, 'Nonfiction', 'Floor 1 Column 10', 'Aqua'),
(23, 'Studies', 'Floor 3 Column 1', 'Violet'),
(24, 'Toddler', 'Floor 1 Column 3', 'Red');