ALTER TABLE ordering DROP CONSTRAINT SYS_C008809;

ALTER TABLE ordering
ADD CONSTRAINT SYS_C008809
FOREIGN KEY (LuserName) REFERENCES librarian(LuserName) ON DELETE CASCADE;

ALTER TABLE librarian MODIFY LibrarianName varchar2(40);
